# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Change.create!([
  { :name => "CR0815", :load_on_test => "2013-09-17", :load_on_int => "2013-09-17", :load_on_prod => "2013-09-17", :customer_contact_id => 2, :user_id => 2, :tracker_id => 7552854, :comment => "", :created_at => "2013-09-17 21:45:02", :updated_at => "2013-10-28 22:23:27", :number => 1037, :change_status_id => 3, :loaded_on_test => nil, :loaded_on_int => nil, :loaded_on_prod => nil, :start_of_user_acceptance_test => nil, :start_of_usage_on_prod => nil, :belongs_to_release => nil, :short_description => "DCS - Adapt Check Robot to new Groundservice LH CKI Business Update", :airline_id => nil, :external_provider => nil, :priority => nil, :accepted_at => nil, :offer_due_at => nil, :offer_delivered_at => nil, :ordered_at => nil, :change_log => nil },
])



ChangeStatus.create!([
  { :number => 1, :status => "registered", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 2, :status => "awaiting evaluation", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 3, :status => "evaluation in progress", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 4, :status => "evaluated (rough)", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 5, :status => "evaluated final", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 6, :status => "ordered", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 7, :status => "specification in progress", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 8, :status => "specified", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 9, :status => "realization in progress", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 10, :status => "realized", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 11, :status => "ready for acceptance", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 12, :status => "accepted", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 13, :status => "online", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 14, :status => "online & closed", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 15, :status => "undefined?", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 16, :status => "postponed", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" },
  { :number => 17, :status => "awaiting feedback", :created_at => "2013-10-06 12:55:05", :updated_at => "2013-10-06 12:55:05" }
])



CustomerContact.create!([
  { :name => "Steffen H", :email => "steffen.h@example.de", :created_at => "2013-09-27 18:43:59", :updated_at => "2013-09-27 18:43:59" }
])



Micropost.create!([
  { :content => "New change tracker tool experiments", :user_id => 1, :created_at => "2013-08-31 14:43:22", :updated_at => "2013-08-31 14:43:22" },
  { :content => "Still looking ugly though", :user_id => 1, :created_at => "2013-08-31 14:43:47", :updated_at => "2013-08-31 14:43:47" }
])



User.create!([
  { :name => "Martin G", :email => "martin.g@example.com", :created_at => "2013-08-31 14:27:08", :updated_at => "2013-08-31 14:27:08" },
])


